name: build_push_docker

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tag
        id: set_tag
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"
          RUNS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/runs?event=pull_request&status=completed&pull_request=${PR_NUMBER}" | jq -r '.workflow_runs | length')
          IMAGE_TAG=${PR_NUMBER}.${RUNS}
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/cicd_assignment:${{ env.IMAGE_TAG }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd_assignment:${{ env.IMAGE_TAG }}

      - name: evaluate_score
        uses: ./.github/workflows/run_check_score.yml
        with:
          script:
            image_tag: ${{ env.IMAGE_TAG }}
